# Generated by Django 6.0.1 on 2026-02-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_client_reservation_nom_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
