# Generated by Django 5.2.8 on 2026-02-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_nni_alter_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nni',
        ),
    ]
