# Generated by Django 5.2.8 on 2026-02-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_reservation_nni'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
