# Generated by Django 6.0.1 on 2026-01-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kilometrage', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('louee', 'Louée'), ('maintenance', 'Maintenance')], max_length=20)),
            ],
        ),
    ]
