# Generated by Django 6.0.1 on 2026-01-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='matricule',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
