# Generated by Django 6.0.1 on 2026-01-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0002_voiture_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='prix_jour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
