# Generated by Django 6.0.1 on 2026-02-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0003_alter_voiture_prix_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('louee', 'Louée'), ('maintenance', 'Maintenance')], default='disponible', max_length=20),
        ),
    ]
