# Generated by Django 5.2.8 on 2026-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0004_alter_voiture_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
