# Generated by Django 6.0.1 on 2026-02-15 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_id'),
        ('transactions', '0002_alter_transaction_id'),
        ('voitures', '0006_alter_voiture_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='categorie',
            field=models.CharField(blank=True, choices=[('ENTRETIEN', 'Maintenance'), ('ASSURANCE', 'Insurance'), ('REPARATION', 'Repair'), ('CARBURANT', 'Fuel'), ('AUTRE', 'Other')], help_text='Category is required only for DEPENSE type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Associated reservation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voiture',
            field=models.ForeignKey(blank=True, help_text='Associated vehicle (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='voitures.voiture'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Transaction creation date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Optional transaction description', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('REVENU', 'Revenue'), ('DEPENSE', 'Expense')], help_text='Type of transaction: Income or Expense', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'date'], name='transaction_type_1ffefc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['voiture', 'date'], name='transaction_voiture_cf254a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reservation'], name='transaction_reserva_13b4c3_idx'),
        ),
    ]
